language: node_js
node_js:
  - 'node'
cache:
  yarn: true
before_deploy: yarn global add now
deploy:
  - provider: script
      script: bash scripts/deploy_staging_app.sh
      skip_cleanup: true
      on:
        branch: master
  