language: node_js
node_js:
  - 'node'
cache:
  yarn: true
before_deploy: yarn global add now
deploy:
  - provider: script
    script: now --token $NOW_TOKEN --public
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
  - provider: script
      script: bash scripts/deploy_staging_app.sh
      skip_cleanup: true
      on:
        branch: master